### ISSUE TITLE
Bookmark 

### ISSUE THREAD

**Issue by Digitalmatrix2** [OfficeDev/office-store-docs#122]
Hyw guys can I offer a suggestion. can we bookmark theses pages 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da4b471b-b69a-2843-e9dc-dd5816a3ba53
* Version Independent ID: 5d9bf895-6877-8920-1ab5-b238a3d6960d
* Content: [Create your AppSource listing](https://docs.microsoft.com/en-us/office/dev/store/office-store-listing)
* Content Source: [docs/office-store-listing.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/office-store-listing.md)
* Service: **unspecified**
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@Digitalmatrix2 thank you for submitting this feature request, but issues in this GitHub repository (**OfficeDev/office-store-docs**) are intended for reporting errors/problems with the AppSource [documentation](https://docs.microsoft.com/en-us/office/dev/store/submit-to-the-office-store). Therefore I'm closing this issue, but please consider logging this feature request in [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=80118). The product team considers feature requests in UserVoice as one factor when prioritizing future work.
