### ISSUE TITLE
[LOC] Link redirects a non existing page

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/office-store-docs#125]
There is a link which redirects to a non existing page.

**Repro steps**:
1. Go to [https://docs.microsoft.com/en-us/office/dev/store/submit-sharepoint-add-ins-for-office-365-operated-by-21vianet-in-china](https://docs.microsoft.com/en-us/office/dev/store/submit-sharepoint-add-ins-for-office-365-operated-by-21vianet-in-china)
2. See the "21Vianet" link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects a existing page

![image](https://user-images.githubusercontent.com/16706698/40915702-5c40065e-67fd-11e8-914c-ce66df5e6a10.png)

**Comment by Linda-Editor** [comment]
Fixed link by removing the ".en"; new link is http://www.21vianet.com
