### ISSUE TITLE
[LOC] Link redirects to 404 page

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/office-store-docs#126]
There is a link which redirects to a non existing page

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/office/dev/store/upload-package
2. GH https://github.com/OfficeDev/office-store-docs/blob/live/docs/upload-package.md 
3. See the "Create the package for your Microsoft Teams app" link

**Actual results:**
Link redirects to a non existing page
**Expected results:**
Link redirects a existing page

Image:
![gh_officestore](https://user-images.githubusercontent.com/16706698/41146541-f939b50a-6b03-11e8-8d60-a5b45c0ba2e7.PNG)

**Comment by Linda-Editor** [comment]
This file was moved to a different folder, hence the break. The new file name is https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package; I replaced the 404 link with this one.
