### ISSUE TITLE
Respond to customer reviews in AppSource - needs to be updated perhaps

### ISSUE THREAD

**Issue by shaipetel** [OfficeDev/office-store-docs#134]
When we visit the app page and go over comments, logged in as the same user used to submit the app to the store, we only have a "report abuse" link near reviews. the "comment" link is not available.
Please clarify where this link is or why this option is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc80e015-a389-193a-5e65-93b16e6eff59
* Version Independent ID: 188d2a91-ad03-750f-8d78-d3d5f134624b
* Content: [Create effective listings in AppSource and within Office](https://docs.microsoft.com/en-us/office/dev/store/create-effective-office-store-listings#respond-to-customer-reviews-in-appsource)
* Content Source: [docs/create-effective-office-store-listings.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/create-effective-office-store-listings.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Alan1Mulhall** [comment]
Sorry for the delay here - I'll update this page to reflect that we don't currently support responding to reviews. Apologies for this!

**Comment by shaipetel** [comment]
@Alan1Mulhall thanks, but are you going to add this option? It is very much needed for vendors.

See, some times a user tries to install a product to do something the product isn't meant to do or he doesn't understand the product and leaves a bad review.

Other times perhaps there was a temporary issue that got addressed and fixed.

Responding to these comments and reviews is of great value both for the vendors and for people reading the reviews.

**Comment by Alan1Mulhall** [comment]
Thanks for the feedback @shaipetel . We're working with the AppSource team to provide this feature again for all app types supported in AppSource, but unfortunately I can't give an ETA quite yet. It's definitely top of mind for us though.

**Comment by kbrandl** [comment]
@shaipetel thank you for submitting this feature request, and @Alan1Mulhall thank you for acknowledging that the product team is aware of this feature request. Since this GitHub repository (**OfficeDev/office-store-docs**) is for reporting errors/issues with the AppSource [documentation](https://docs.microsoft.com/en-us/office/dev/store/submit-to-the-office-store), I'm closing this issue.
