### ISSUE TITLE
No guidelines about manifest version # changing

### ISSUE THREAD

**Issue by stephenegriffin** [OfficeDev/office-store-docs#15]
I just had an application rejected because I changed my manifest but did not increment my manifest version. While it may be obvious to some that you should increment your version, while there may be technical reasons this should be done, nothing in the guidelines even suggests this.

Recommendation: If this is an actual requirement, add it to the guidelines.

Specifically referencing this page: https://dev.office.com/officestore/docs/validation-policies

**Comment by stephenegriffin** [comment]
Section 10 might be the appropriate place to insert the guideline

**Comment by stephenegriffin** [comment]
I see the FAQ (office-store-submission-faq.md) does say this "You must resubmit add-ins with an updated manifest that includes a new version number. You must also make sure to update the version number in the submission form to match the version number of the new manifest."

That's fine - but if it's not in the guidelines it's not in the guidelines. The FAQ should not have subtle guidelines sprinkled throughout it.

**Comment by Lauragra** [comment]
Hi Stephen, thanks for your feedback. We'll look into updating/clarifying our documentation in the next few days. We'll respond back when we've published an update.

**Comment by lindalu-MSFT** [comment]
Added guideline as a note in section 10.3
