### ISSUE TITLE
Send customer to the rating page from the add-in

### ISSUE THREAD

**Issue by vtiti** [OfficeDev/office-store-docs#155]
[The documentation](https://docs.microsoft.com/en-us/office/dev/store/create-effective-office-store-listings#use-ratings-and-reviews) suggests to send the customer directly to the rating page, after a while the user using the add-in.

How can I determine the link for my add-in's feedback/rating page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc80e015-a389-193a-5e65-93b16e6eff59
* Version Independent ID: 188d2a91-ad03-750f-8d78-d3d5f134624b
* Content: [Create effective listings in AppSource and within Office](https://docs.microsoft.com/en-us/office/dev/store/create-effective-office-store-listings#use-ratings-and-reviews)
* Content Source: [docs/create-effective-office-store-listings.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/create-effective-office-store-listings.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Alan1Mulhall** [comment]
You can find the URL by going to "my add-ins" in the Office client, and selecting "rate and review" from the options panel. 

The basic form of the URL will be like below, but you need to substitute your assetID value in. The assetID can be found in the URL of your AppSource listing.
https://store.office.com/writereview.aspx?assetid=WA104211266
