### ISSUE TITLE
Can I edit release date *after* an app is approved?

### ISSUE THREAD

**Issue by david-davidson** [OfficeDev/office-store-docs#165]
If I want to start the approval process before knowing an exact release date, I might want to:
* Submit my app for approval with a distant release date
* Complete the full approval process
* Later, edit the release date to move it forward

Is it possible to edit the release date after an app is approved? If possible, does that require going through the approval process again?

(P.S. Thanks for the great docs!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c1670eb-6ba2-88aa-6162-46bd4e2395dc
* Version Independent ID: 5aaa87d0-35d8-32bf-9fa0-56a1473a984e
* Content: [Use the Seller Dashboard to submit your solution to AppSource](https://docs.microsoft.com/en-us/office/dev/store/use-the-seller-dashboard-to-submit-to-the-office-store)
* Content Source: [docs/use-the-seller-dashboard-to-submit-to-the-office-store.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/use-the-seller-dashboard-to-submit-to-the-office-store.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Lauragra** [comment]
Thanks for reaching out. @PhilSmail , can you please respond? Thanks.

**Comment by david-davidson** [comment]
@PhilSmail @Lauragra Hi, have you learned anything more about editing the release date?

Thanks!

**Comment by PhilSmail** [comment]
Sorry, just seeing this now!

The most common mechanism is to publish with today's date (or a previous date) which means it will publish as soon as it's approved

If you need a specific release date then set the date in the future and we it can be changed. PM me for details
