### ISSUE TITLE
The Dynamics PDF has a broken link

### ISSUE THREAD

**Issue by pablodiazgutierrez** [OfficeDev/office-store-docs#174]
I can't download (or find independently) the MicrosoftMarketplacesLeadIntegrationSolution_1_0_0_0_target_CRM_6 file required to setup Dynamics for capturing new leads. Is there an updated version of this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79d9f7f-704a-9e9e-3f8a-49969540cbc7
* Version Independent ID: 6ce4198c-665e-097c-1db1-d47c5c8d043c
* Content: [Add lead management details for your Office Add-ins in the Seller Dashboard](https://docs.microsoft.com/en-us/office/dev/store/add-lead-management-details)
* Content Source: [docs/add-lead-management-details.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/add-lead-management-details.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Alan1Mulhall** [comment]
Hi Pablo,

I'm not able to repro this personally - the Dynamics docs I see available are pointing to:
https://smpprodresources.azureedge.net/partnerresources/Partner%20instructions%20-%20Dynamics%20365%20(CRM).pdf

Could you see if these work for you, or point me to where you're seeing the broken link?

**Comment by pablodiazgutierrez** [comment]
Thanks Alan, sorry, I should have clarified that I see the PDF too, but inside the PDF it refers to a [link to download a solution config file](https://testdriveaccount.blob.core.windows.net/testdrivecon/MicrosoftMarketplacesLeadIntegrationSolution_1_0_0_0_target_CRM_6.1_managed.zip) and that's broken. The fact that the subdomain begins with `testdriveaccount` makes me suspicious.

**Comment by Lauragra** [comment]
@Alan1Mulhall , did you investigate whether the link is still valid? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
As @pablodiazgutierrez noted, in the pdf the link to download the solution is invalid:
https://testdriveaccount.blob.core.windows.net/testdrivecon/MicrosoftMarketplacesLeadIntegrationSolution_1_0_0_0_target_CRM_6.1_managed.zip

Can the pdf be updated with a valid link or to include an alternative way to download the solution?

**Comment by ElizabethSamuel-MSFT** [comment]
@pablodiazgutierrez We're working on getting these docs updated. No ETA yet though. Thanks.

**Comment by mscharlock** [comment]
@ElizabethSamuel-MSFT do you know if there is any update on this? I'm combing through the backlog of issues in the store repo. Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@Alan1Mulhall Any update here? Thx.

**Comment by ElizabethSamuel-MSFT** [comment]
This issue is quite old and the docs have changed in the interim [current lead management docs](https://learn.microsoft.com/partner-center/marketplace-offers/partner-center-portal/commercial-marketplace-get-customer-leads). Closing.

**Comment by matetra** [comment]
Hi @ElizabethSamuel-MSFT ,
it seems that the link for Microsoft Marketplace Lead Writer solution is still broken in the [current docs](https://learn.microsoft.com/en-us/partner-center/marketplace-offers/partner-center-portal/commercial-marketplace-lead-management-instructions-dynamics#install-the-solution).

It gives the following error:
![image](https://github.com/user-attachments/assets/cf81ce79-3b0c-461e-b064-d049c3330074)


Can you help me how can I download it?
As far as I understand it is a must for sending leads to our Dynamics Sales App.

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for letting us know. Reopening.

**Comment by cwatson-sidub** [comment]
Still an issue...

**Comment by ElizabethSamuel-MSFT** [comment]
@matetra @cwatson-sidub This is being updated in the documentation. In the meantime, try the following link.

[Microsoft Marketplace Lead Writer solution](https://referralsconnector.azurefd.net/documentation/MicrosoftMarketplacesLeadIntegrationSolution_1_0_0_0_target_CRM_6.1_managed.zip)

**Comment by ElizabethSamuel-MSFT** [comment]
This should now be fixed in the documentation so closing this issue. Thanks again for letting us know about this.

**Comment by matetra** [comment]
@ElizabethSamuel-MSFT thank you for your help
