### ISSUE TITLE
Monetizing VSTO Add-Ins

### ISSUE THREAD

**Issue by jlongo62** [OfficeDev/office-store-docs#183]
It is really unclear in this page that VSTO add-ins are not supported (unless they are) but I can't figure out how to publish one for monetization. Is there a way to monetize VSTO Add-Ins ? If so do you have a sample walk-through ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6cdb21-e624-a60d-9dff-e880b28643be
* Version Independent ID: 56b84478-0f73-93e1-6393-0a4e50fe4426
* Content: [Make your solutions available in AppSource and within Office - AppSource](https://docs.microsoft.com/en-us/office/dev/store/submit-to-the-office-store)
* Content Source: [docs/submit-to-the-office-store.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/submit-to-the-office-store.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
VSTO add-ins are not supported in AppSource. To monetize a VSTO add-in, you need to market it in some other way, such as on a website. I will add a note to this effect in the article.

**Comment by jlongo62** [comment]
Unfortunately without the store installing win 10 desktop applicatiins is nearly impossible especially if you are inside an enterprise. I’ve tried. It is due to trust issues and certs.

Regards,
Joseph Longo
Microsoft Stack Developer
(703) 819-8048

________________________________
