### ISSUE TITLE
[LOC] Broken link

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/office-store-docs#186]
There is a broken link in an article

**repro steps**:
1. go to [https://docs.microsoft.com/en-us/office/dev/store/add-license-checks-to-office-and-sharepoint-add-ins](https://docs.microsoft.com/en-us/office/dev/store/add-license-checks-to-office-and-sharepoint-add-ins)
2. Search for "getUserIdentityTokenAsync" link
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link should redirect correctly

**GH article**:
https://github.com/OfficeDev/office-store-docs/blob/live/docs/add-license-checks-to-office-and-sharepoint-add-ins.md

![image](https://user-images.githubusercontent.com/16706698/52125649-6d42f800-262d-11e9-94b2-8a93374b90be.png)

**Comment by ElizabethSamuel-MSFT** [comment]
The change should go live soon. Closing out.

**Comment by ElizabethSamuel-MSFT** [comment]
Actually, the change went live yesterday. Thanks.
