### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [OfficeDev/office-store-docs#195]
There is a broken link within an article.

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/office/dev/store/validation-policies?context=outlook/context
2. Search for the "Guidelines for Power BI visuals with additional purchases"
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects correctly

**GH article:**
https://github.com/OfficeDev/office-store-docs/blob/master/docs/validation-policies.md

**Comment by Lauragra** [comment]
Fixed link in PR #196.
