### ISSUE TITLE
Validation Policies Should Reference iOS Guidelines

### ISSUE THREAD

**Issue by stephenegriffin** [OfficeDev/office-store-docs#20]
validation-policies.md needs to incorporate the additional iOS guidelines given in https://github.com/OfficeDev/office-js-docs/blob/master/docs/develop/develop-office-add-ins-for-the-ipad.md

**Comment by Lauragra** [comment]
Thanks for the feedback. We updated policy 10.8 to include the iOS guidelines. The update should be live on the site shortly.
