### ISSUE TITLE
How can I host app on appsource store as independent contribute 

### ISSUE THREAD

**Issue by ashishp1709** [OfficeDev/office-store-docs#211]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da4b471b-b69a-2843-e9dc-dd5816a3ba53
* Version Independent ID: 5d9bf895-6877-8920-1ab5-b238a3d6960d
* Content: [Create your AppSource listing - AppSource](https://docs.microsoft.com/en-us/office/dev/store/office-store-listing)
* Content Source: [docs/office-store-listing.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/office-store-listing.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
@ashishp1709 - Do you still require assistance on this issue? I am going to close this issue based on age, but I am happy to reopen if you comment again on this thread. Thank you!
