### ISSUE TITLE
Contradictory recommendation of long description

### ISSUE THREAD

**Issue by jon3321** [OfficeDev/office-store-docs#218]
Under "Effective Long Descriptions" you say "Most users read between 300 and 500 words.". In the table under "Apply guidelines for title and description length", for Long description the recommended length is "300-500 characters". These recommendations are contradictory. I presume the table should say "300-500 words" rather than "300-500 characters"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc80e015-a389-193a-5e65-93b16e6eff59
* Version Independent ID: 188d2a91-ad03-750f-8d78-d3d5f134624b
* Content: [Create effective listings in AppSource and within Office - AppSource](https://docs.microsoft.com/en-us/office/dev/store/create-effective-office-store-listings#apply-guidelines-for-title-and-description-length)
* Content Source: [docs/create-effective-office-store-listings.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/create-effective-office-store-listings.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Alan1Mulhall** [comment]
Thanks for reporting! This has since been fixed.
