### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [OfficeDev/office-store-docs#229]
There is a broken link within an article.

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/office/dev/store/add-license-checks-to-office-and-sharepoint-add-ins
2. Search for the "getUserIdentityTokenAsync"
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects correctly

**GH article:**
https://github.com/OfficeDev/office-store-docs/blob/master/docs/add-license-checks-to-office-and-sharepoint-add-ins.md
![image](https://user-images.githubusercontent.com/47977325/66305067-d7b7e080-e8fe-11e9-8da3-4e283581ce0f.png)

**Comment by Lauragra** [comment]
@ElizabethSamuel-MSFT , can you help identify the target URL for the broken link? Thanks.
