### ISSUE TITLE
Who to turn to for support?

### ISSUE THREAD

**Issue by arahant2001** [OfficeDev/office-store-docs#237]
In the seller dashboard, it says "Account pending approval", but on my developer account (https://partner.microsoft.com/en-US/dashboard/account/management)  the account status is "Authorized". It has been this way for days now, and I'm at a loss to figure out what I should do. Who can I turn to for support on this matter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46ba792e-3604-2387-df01-658d8a58d413
* Version Independent ID: a4bd95e7-bc69-9aaf-3747-f9eab9f67556
* Content: [AppSource submission FAQ - AppSource](https://docs.microsoft.com/en-us/office/dev/store/office-store-submission-faq)
* Content Source: [docs/office-store-submission-faq.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/office-store-submission-faq.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @arahant2001 - I hope you found some support! Based on the age of this issue I am closing it, but let us know if you need assistance with a comment on this thread and I will go ahead and reopen it. Thank you!
