### ISSUE TITLE
Not clear on when/where add-ins can be activated.

### ISSUE THREAD

**Issue by mcvic1rj** [OfficeDev/office-store-docs#24]
It appears that addons cannot be activated when you open either a msg or eml attachment. It looks like this is not documented anywhere.

**Comment by PhilSmail** [comment]
Hi, I'm not sure I understand the question but this is probably better to ask on stackoverflow. tag the message with office-js

**Comment by mcvic1rj** [comment]
Hi, I raised this issue per StepheneGriffin. You can check his comment here: https://github.com/stephenegriffin/MHA/issues/12#issuecomment-298379289

**Comment by jasonjoh** [comment]
Thanks for the feedback @mcvic1rj. This is "kind of" documented here: https://dev.office.com/docs/add-ins/outlook/troubleshoot-outlook-add-in-activation:

> If your Outlook add-in is a read add-in and is supposed to be activated when the user is viewing a message (including email messages, meeting requests, responses, and cancellations) or appointment, even though these items generally support add-ins, there are exceptions if the selected item is one of the following:
>
> - Protected by Information Rights Management (IRM).
> - In S/MIME format or encrypted in other ways for protection.
> - A draft (does not have a sender assigned to it), or is in the Outlook Drafts folder.
> - In the Junk Email folder.
> - A delivery report or notification that has the message class IPM.Report.*, including delivery and Non-Delivery Report (NDR) reports, and read, non-read, and delay notifications.
> - A .msg file that is attached to another message or was opened from the file system.

I say "kind of" because this definitely could be more discoverable and explicit. I'll take a work item to address this, but it will be a while before I can get to it.

**Comment by lindalu-MSFT** [comment]
@jasonjoh Has this been addressed? Let me know if I can help resolve and close this issue.

**Comment by jasonjoh** [comment]
Linda yes, it's doc'ed here: https://docs.microsoft.com/en-us/outlook/add-ins/. However, I'm noticing that it doesn't include .eml files in the description. Should probably add that. @ElizabethSamuel-MSFT may be able to help there :)
