### ISSUE TITLE
Office 365 validation test results "Contact us"

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-store-docs#260]
I received feedback for an AppSource submission, and there are a couple of ambiguous comments in the document that I need more information about. Inside the PDF, it says:

> Please address the validation errors before we publish your solution to the storefronts on AppSource and within Office products.
> 
> Next steps:
> * Contact us. We can help you resolve your validation issues more quickly.
> * Address the issues listed and resubmit your solution.
> * Confirm you’re following best practices. Apply our best practice guidelines to your UX design.

The problem is, there is no contact information or link for WHO to contact. It just says "Contact us". 

Who should I be contacting regarding in-progress submissions, and where do I find this contact information?

**Comment by bryanroth** [comment]
Same problem. The contact us link at the bottom of the report links to an empty email address.

**Comment by mscharlock** [comment]
@mikeald Just wanted to make sure you were aware of this issue! Thanks

**Comment by mscharlock** [comment]
Hi all, I believe this issue should be fixed in the new validation flow. If not, go ahead and leave a comment on this issue and I will re-open it to investigate. Thanks!
