### ISSUE TITLE
On-send restrictions

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-store-docs#261]
Shouldn't this page also reference this warning "Add-ins that use the on send feature aren't allowed in AppSource"? (from https://docs.microsoft.com/en-ca/outlook/add-ins/outlook-on-send-addins?tabs=windows)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c63f26-72a6-8963-e4f0-88d4aa4c6a38
* Version Independent ID: 9bbc7ac3-9f91-bcde-44d3-3952c9133257
* Content: [Validation policies for apps and add-ins submitted to AppSource (version 2.2) - AppSource](https://docs.microsoft.com/en-us/office/dev/store/validation-policies?source=docs#feedback)
* Content Source: [docs/validation-policies.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/validation-policies.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@elegault Thanks for letting us know about this. We've updated the policy to include this restriction.

Thanks.
