### ISSUE TITLE
Will requirements to test Office Addins on Windows 7 be dropped?

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-store-docs#262]
With Windows 7 leaving extended support on January 14th, 2020 (basically in a month), will the requirements for testing Office Online add-ins in Windows 7 be dropped as well?

**Comment by mscaitlina** [comment]
I do not have an update at this time, but expect there will be one in the new year.

**Comment by sureshjoshi** [comment]
@mscaitlina Thanks for the reply! 

Could you please direct me as to where I can purchase Windows 7 on the Microsoft store? 

I need to install Windows 7, and a desktop version of Word (I have licenses for this), to support my Office Store add-in submission (it's been rejected for failing on Windows 7, Word 2016, IE11). 

However, I can't seem to find it (Windows 7) anywhere for legal (or, reputable) purchase.

**Comment by mscaitlina** [comment]
I'm sorry for the delay over the holidays. You can purchase Windows 7 on amazon: https://www.amazon.com/Microsoft-Windows-Home-Premium-GFC-01042/dp/B004STQFJ4/ref=sr_1_9?keywords=windows+7&qid=1578342354&sr=8-9

**Comment by sureshjoshi** [comment]
Hi @mscaitlina, to close the loop on this - I feel like the Microsoft Edge/IE test environments are a FAR better solution to this problem. I'm also surprised they don't appear to be mentioned in the documentation anywhere.

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I'd like to recommend they are added in, mentioning that they're 90 day licensed.

**Comment by mscaitlina** [comment]
Thank you! We'll follow up on that.
