### ISSUE TITLE
Outlook-email-paid-add-ins

### ISSUE THREAD

**Issue by deyanskiq** [OfficeDev/office-store-docs#296]
As I understand from the documentation if I want to sell through Microsoft and not to implement my own payment model the add-in will be accessible only to users with work/school emails and people with outlook emails won't be able to use it, is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e475466-5221-4374-a8e2-fbc5a5645683
* Version Independent ID: 26a61b4c-d607-b2c4-4432-542cd1072726
* Content: [Monetize your Office 365 add-in through Microsoft Commercial Marketplace - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/monetize-addins-through-microsoft-commercial-marketplace#feedback)
* Content Source: [docs/monetize-addins-through-microsoft-commercial-marketplace.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/monetize-addins-through-microsoft-commercial-marketplace.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Lauragra** [comment]
@mikeald , assigning to you to follow up. Thanks.

**Comment by mscharlock** [comment]
Hi @deyanskiq - Do you still need help with this issue? I am going through this repo to close out old issues. If you still need help, go ahead and leave a comment on this thread and I will reopen the issue. For now I am going to close. Thanks!
