### ISSUE TITLE
No Azure Blob Setting in Partner Settings

### ISSUE THREAD

**Issue by adrianmolzon** [OfficeDev/office-store-docs#297]
When I load up the Partner Center after creating an Azure Blob in the Azure Portal, I only have five options, with the missing option being 'Azure Blob'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b53e9c-2999-4659-f3b2-ad8b781539b9
* Version Independent ID: 271e7a8d-d27e-d00b-8680-f92f6f3b00a6
* Content: [Add setup details for your Office solution - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/add-setup-details#feedback)
* Content Source: [docs/add-setup-details.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/add-setup-details.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by adrianmolzon** [comment]
This is in the Lead Management Edit file under the Lead destination dropdown menu.

**Comment by mscharlock** [comment]
@mikeald Is this a bug that has been resolved? Thanks!

**Comment by mikeald** [comment]
@mscharlock I'm not the right person for this issue. This is an Azure issue in partner center not M365 or validation. I would direct them to  aka.ms/marketplacepublishersupport

**Comment by mscharlock** [comment]
Hi @adrianmolzon - if you can go ahead and contact folks through aka.ms/marketplacepublishersupport, that would be great. Because of the age of this issue, I will be closing it but if you need additional assistance I can reopen the thread if you comment on it. Thank you!
