### ISSUE TITLE
Email verification for becoming MPN developer does not work.  I get an error when i click the verification button.  Also, when I try to 'resend verification email' that does not work either.  Anybody have experience with this?

### ISSUE THREAD

**Issue by receiptq** [OfficeDev/office-store-docs#300]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23aff8f8-a2cc-2722-d806-08d4a8e519ad
* Version Independent ID: 913f49b5-797d-351f-d8f0-59e68f7153f0
* Content: [Make your solutions available in Microsoft AppSource and within Office - Microsoft AppSource](https://docs.microsoft.com/en-ca/office/dev/store/submit-to-appsource-via-partner-center)
* Content Source: [docs/submit-to-appsource-via-partner-center.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/submit-to-appsource-via-partner-center.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @receiptq - Do you still need assistance with this issue? I am going through the issues in this repository as they have not been addressed in a while and will be closing this issue because of age. However, if you still need something go ahead and comment and I can reopen the thread. Thanks!
