### ISSUE TITLE
Monetising Office addin using own payment model

### ISSUE THREAD

**Issue by AndreyBestCode** [OfficeDev/office-store-docs#301]
I would like to monetise Excel add-in, by creating my own payment and licensing model. I would like allow users to download add-in for free from office store, use it for some time free of charge and later when the initial free offer is expired I will give user and option to buy a licence from my own portal. The payment collection system will be implemented using trusted payment collection provider system like Strip or other. Can I implement my own licensing / payment system? My adding will contact my licensing API check that the user is fully licensed before allowing user to user the services. Is this model comply with MS monetising guidance?

**Comment by Lauragra** [comment]
Hi @AndreyBestCode , yes, you are free to implement your own licensing model and we will display your add-in in the stores when you submit it for validation. Feel free to reopen the issue if you have further questions. Thanks.
