### ISSUE TITLE
Feedback on documentation - "Authorize to Microsoft Graph" is confusing and seems out of place

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/office-store-docs#303]
Just trying to help with the docs...

The section title is "Build an Azure AD connected add-in" and goes on to describe the 3-states of your add-in. Got that. Then the section ends with "to authenticate with Azure AD, see "Authorize to Microsoft Graph" which goes to a page titled "Authorize to Microsoft Graph without SSO"???  Not clear why the add-in cares about Microsoft Graph. I believe it's to allow the user to login to AAD to get user information from a tenant but that's not really clear. 

Maybe a sentence or two as to why you're doing this and why the link to "Authorize to Microsoft Graph".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e475466-5221-4374-a8e2-fbc5a5645683
* Version Independent ID: 26a61b4c-d607-b2c4-4432-542cd1072726
* Content: [Monetize your Office 365 add-in through Microsoft Commercial Marketplace - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/monetize-addins-through-microsoft-commercial-marketplace#feedback)
* Content Source: [docs/monetize-addins-through-microsoft-commercial-marketplace.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/monetize-addins-through-microsoft-commercial-marketplace.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
@Lauragra can you weigh in on this? Thanks!

**Comment by Lauragra** [comment]
@Rick-Kirkham , I think you own add-in authentication? Can you take a look please?

**Comment by Rick-Kirkham** [comment]
@jimbarrett33 I've replaced that link with two links that more appropriate. It should be republished in the next few days.
