### ISSUE TITLE
'Overview' link does not link to a page with the 'Create New' option

### ISSUE THREAD

**Issue by LoveSponge** [OfficeDev/office-store-docs#304]
could be to do with some behind-the-scenes updates happening to that page but this is the link location:
https://partner.microsoft.com/dashboard/office/overview

and this is the link it sends you to:
https://partner.microsoft.com/en-us/dashboard/directory

What's more, i seem to be unable to 'get started' with the 'Office Store' developer program because it asks me for company details when my company has already signed up and is affiliated with Partner Center... PLEASE HELP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 212133ca-1a51-d0fd-4108-32508cbc20a7
* Version Independent ID: 45ee8995-57c3-2f16-779d-060cf7be1721
* Content: [Submit your Office solution to Microsoft AppSource via Partner Center - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/use-partner-center-to-submit-to-appsource#feedback)
* Content Source: [docs/use-partner-center-to-submit-to-appsource.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/use-partner-center-to-submit-to-appsource.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Lauragra** [comment]
Hi, we'll look into the link question. In the meantime, please see if this article helps answer your question about the company account: https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/company-work-accounts. Thanks.

**Comment by LoveSponge** [comment]
Hi Laura,

Thanks for the quick response to my query.

I tried following the link you provided, and it sent me on to make sure the company is set up, which it is.

Maybe you can help me:
I have created an Outlook add-in and am trying to submit it for review to Microsoft. Our company has been set up as a publisher and i can see the publisher details on partner network.

The documentation seems to be outdated as the link names it speaks about are not visible in the current MPN Dashboard page, or any other sub-page; 
I've attempted to activate the 'Office Store' offer from the dashboard page, the problem is that it asks me to enter my email address, which leads me to a page that tells me my email address is already affiliated with MPN and to continue signing in. 
Continuing it then asks me to fill out company information, which i have tried but it tells me the publisher exists.... Which is true because i can see the publisher has been set up within MPN. 
I cannot seem to progress beyond that point to actually submitting my add-in...

Any help is appreciated and i thank you in advance for your time.

**Comment by Lauragra** [comment]
Hi,
It might be more expedient for you to file a support ticket here, and they can help you specifically with your account:
https://aka.ms/marketplacepublishersupport

Thanks,
Laura
