### ISSUE TITLE
manifest file shows in uploading status from more than 24 hours

### ISSUE THREAD

**Issue by abhisheknene007** [OfficeDev/office-store-docs#313]
Hi Team, 
we are currently working on deploying our sample add-in to office store. we have added our package manifest file in packages tab. Although it shows in uploading status from last 24 hours and we didn't received any error while uploading.  

Please suggest. we have also tried removing the package and adding again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c8e5a54-3d66-8917-7ecc-1b8d01420338
* Version Independent ID: 4a71b13e-522f-042f-0971-81061466a902
* Content: [Upload your package to Microsoft AppSource - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/upload-package)
* Content Source: [docs/upload-package.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/upload-package.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @abhisheknene007 - Do you still need assistance with this issue? I am closing this thread for now because of the age of the issue, but please re-comment on the thread if you still need anything and we can help resolve. Thanks!

**Comment by abhisheknene007** [comment]
Ok will check the issue if still persists I will drop a comment on the
thread.
