### ISSUE TITLE
Menu Typo

### ISSUE THREAD

**Issue by mormond** [OfficeDev/office-store-docs#318]
There is a typo on the LH menu for this page - it reads "Mange" instead of "Manage"

![image](https://user-images.githubusercontent.com/13424886/85126758-01632e80-b226-11ea-8bcc-d49f2efc3e17.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52857d74-7e76-cbe7-5f3d-bce27e369a46
* Version Independent ID: 174b8aa7-d22c-7a0d-fdb9-66c3e0cbfd99
* Content: [Manage names in Partner Center - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/manage-solution-names)
* Content Source: [docs/manage-solution-names.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/manage-solution-names.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Lauragra** [comment]
Thanks; fixed in PR #319
