### ISSUE TITLE
Publishing JS Add-In on Microsoft Partner Center

### ISSUE THREAD

**Issue by t-lm** [OfficeDev/office-store-docs#328]
Situation: 
Microsoft Excel JS Add-in - Trying to publishing on App Source - Fonctionning add-in (local/ azure)

Issue: 
The following error is raised when trying to publish the app on Microsoft Partner Center and trying to upload the package (e.g. in my case manifest.xml): "Package acceptance validation error: manifest.xml is an unknown package type. Please name your file with the appropriate file extension."

Question:
What is the correct way to publish on App source for Excel JS Add-in? Is it documented somewhere?

Thank you

**Comment by mscharlock** [comment]
Hi @t-lm - We have recently updated the documentation on validation and publishing in this repository. Please go ahead and read these new docs and let us know if you still have questions by commenting on this thread. I am going to close this thread for now but if you comment I will go ahead and re-open this. Thank you!

**Comment by t-lm** [comment]
Thanks. Will check it out. Best

Le 13 janv. 2021 à 22:31, Michelle Scharlock <notifications@github.com<mailto:notifications@github.com>> a écrit :



Hi @t-lm<https://github.com/t-lm> - We have recently updated the documentation on validation and publishing in this repository. Please go ahead and read these new docs and let us know if you still have questions by commenting on this thread. I am going to close this thread for now but if you comment I will go ahead and re-open this. Thank you!
