### ISSUE TITLE
Seller Dashboard for U.S. Government Environment

### ISSUE THREAD

**Issue by longnlp** [OfficeDev/office-store-docs#329]
We are using the Seller Dashboard to manage the client id and client secret, and recent we found the SharePoint Online App is not working in U.S. Government environment like GCC High Office 365 tenant. Is there any separated Seller Dashboard for U.S. Government? Thank you!

The other user is facing the same issue here https://sharepoint.stackexchange.com/questions/283831/sharepoint-add-in-client-id-and-secret-for-us-gov-tenancy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf555ecc-94e0-0f23-ab27-b1d2e483fbc5
* Version Independent ID: e0cb668e-05e3-8412-04de-6e24aea97ea5
* Content: [Create or update client IDs and secrets in Partner Center - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/create-or-update-client-ids-and-secrets)
* Content Source: [docs/create-or-update-client-ids-and-secrets.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/create-or-update-client-ids-and-secrets.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
Hi @longnlp - I believe the answer on Stack is still the same at present. I'm going to close this issue for now, but please re-comment on the issue if you still have questions or need something else. Thanks!
