### ISSUE TITLE
Indivudal account for developers 

### ISSUE THREAD

**Issue by schostac** [OfficeDev/office-store-docs#341]
**Individual account for developers** in Partner Centre does not allow to **submit add-ins for Word** - there is no interface for that (more precisely, it always redirects to creating company account) unlike in company account. I've created an add-in for Word but cannot submit to Office Store as an individual. It's not clear from this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd82b4bc-7340-4aff-bc43-5cfea08c24bf
* Version Independent ID: cf756c44-bdef-dd4e-875b-3a792be27bca
* Content: [Open a developer account in Partner Center - Microsoft AppSource](https://docs.microsoft.com/en-us/office/dev/store/open-a-developer-account)
* Content Source: [docs/open-a-developer-account.md](https://github.com/OfficeDev/office-store-docs/blob/master/docs/open-a-developer-account.md)
* Product: **office**
* Technology: ****
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
@mikeald can you confirm this so docs team can update? Thanks!

**Comment by mikeald** [comment]
You can submit a word add-in but you have to select it as an Office Add-in during submission. If you are an individual and don't have an approved partner center ID you can't publish to the app store.

**Comment by schostac** [comment]
0. The wording like

> have an approved partner center ID

is the root cause of I the problems that I have experienced with this Partner Center. What you basically say is that an individual cannot publish without a registered company.

1. If you go to https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish ("**Deploy and publish Office Add-ins**"), then click on "**AppSource**" and go to https://docs.microsoft.com/en-us/office/dev/store/submit-to-appsource-via-partner-center, then click on "**Opening a developer account**" and go https://docs.microsoft.com/en-us/office/dev/store/open-a-developer-account and scroll down, you will find 

> Both types of accounts allow you to submit apps, add-ins, and services. For more info, see Account types, locations, and fees.

The last sentence in the quote redirects nowhere specifically.
So it turns out that I cannot publish add-ins because I do not have a company. To me the documentation is misleading. I've spent a lot of time on the add-in and website, created an individual account, paid the fee for that account, but nothing is in the end. 

2. Why individuals cannot publish without a registered company? Why basically only businesses can publish? That's insane. Image, for example, that GitHub were like that. That kills some potentially useful add-ins for Office at the outset.

**Comment by mscharlock** [comment]
Hi @schostac - Sorry this has been frustrating for you. Thanks for pointing out the redirect bug, I will go ahead and update this section of the documentation because as you say, it is confusing! And thank you for the feedback about the policy, I will let the PM team know about your thoughts.

**Comment by mscharlock** [comment]
Hi @schostac - I have updated the docs and am going to close this issue but let us know if you need assistance with a comment on this thread and I will reopen. Thanks!
