### ISSUE TITLE
Lead Management information doesn't save despite the positive communicate.

### ISSUE THREAD

**Issue by fildnet** [OfficeDev/office-store-docs#36]
When You choose "Edit Lead Management information" in app details, after information and credential input there is a "Your data has been saved successfully" communicate and after returning to the edit page there is no information at all only unchecked "Leave management" I was using a Chrome browser 59.0.3071.115

**Comment by Alan1Mulhall** [comment]
Hi there,

Due to compliance reasons, the form isn't able to pull in your previously entered-data on refresh. Rest assured that if you received the above successful message, your data is indeed saved. Apologies for the confusion here.

**Comment by lindalu-MSFT** [comment]
Closing this issues because there doesn't' appear to be a request to update documentation. If you still feel this is an issue, please open a new issue and please include the link to the documentation source. Thanks, lindalu@microsoft.com
