### ISSUE TITLE
What is lead management and does it actually work?

### ISSUE THREAD

**Issue by viperfx** [OfficeDev/office-store-docs#60]
I am the developer of a Microsoft Teams app and I have configured Azure table details for lead management. 

I know customers have installed the app since I setup lead management but there is no data in the azure table or in the analytics section of the app.

**Comment by Alan1Mulhall** [comment]
Hi there,

Leads are currently only generated for acquisitions made via the web discovery marketplace, [AppSource](https://appsource.microsoft.com/en-us/). As Teams apps are currently not available on AppSource, no leads will be written. 

We'll keep you posted as the lead program for Office developers expands further going forward.

**Comment by lindalu-MSFT** [comment]
@Alan1Mulhall any update here? If not, can you suggest a place to make a note in the documentation? I'm happy to make the change and close this issue. Thanks, lindalu@microsoft.com

**Comment by Alan1Mulhall** [comment]
Hi @lindalu-MSFT , we have a call-out of this effect in the documentation at https://docs.microsoft.com/en-us/office/dev/store/add-lead-management-details
