### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/office-store-docs#95]
Link redirects to 404 error message.

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/office/dev/store/validation-policies
2. Search for "Craft effective AppSource images"
3. Click the link

**Actual results:**
Link redirects to 404
**Expected results:**
Link should redirect to a valid page

**GH article:**
https://github.com/OfficeDev/office-store-docs/blob/live/docs/validation-policies.md

![404](https://user-images.githubusercontent.com/16706698/37393611-d1f8b39a-2771-11e8-871a-3d900971eab3.png)

**Comment by Lauragra** [comment]
Fixed link and republished the content. Thanks!
